---
API_PORT: 8080
BOT_TOKEN:
CHANNELS:
  ANNOUNCEMENTS: 1113007584702627911
  BOT_LOGS: 1390267799863165038
  BOT_PLAYGROUND: 1296529518793588748
  MOUSETRAP: 1319726258493591612
  RULES: 1229425258747138180
DRY_RUN: false
GUILDS:
  JIMS_GARAGE: 1109224479281905787
LOG_CHANNEL:
LOG_DIR: "log"
LOG_FILE: "bot.log"
LOG_LEVEL_FILE: "DEBUG"
LOG_LEVEL_STDOUT: "INFO"
ROLES:
  ADMIN: 1230087912159449108
  BOTS: 1296533955654451270
  GARAGE_MEMBER: 1296535672223698985
  JIMS_GARAGE: 1316312797419929702
  MOD: 1205631095547105290
  VIP: 1128425498540785705
TIMEZONE: "UTC"
YOUTUBE_FEEDS:
  JIMS_GARAGE: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUUTdohVElFLSP4NBnlPEwA"
  TECH_BENCH: "https://www.youtube.com/feeds/videos.xml?channel_id=UCT5B7jBug46N7abnl_izt5w"
