---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discordbot
  namespace: argocd
spec:
  project: default
  sources:
    # Remote GitHub repo (monitored for changes)
    - repoURL: https://github.com/cyberops7/discord_bot.git
      targetRevision: main
      ref: remote
    # Local repo with a kustomization file (applies patches)
    - repoURL: https://your.k8s.repo.url.here
      targetRevision: main
      path: discordbot
  destination:
    server: https://kubernetes.default.svc
    namespace: discordbot
  revisionHistoryLimit: 5
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
